### ISSUE TITLE
Double clan tag on osu! score page

### ISSUE THREAD

**Issue by MF-JEWM** [darkchii/score-inspector-extension#9] opened 2024-07-24 18:35 UTC
There seems to be a bug which causes a user's clan tag to display twice when viewing details page for one of their scores on the main site.

As an example when viewing [this score](https://osu.ppy.sh/scores/1711867460), it says `[GOON] [GOON] decaten` when it should only say `[GOON] decaten` (pictured below)

[![example](https://github.com/user-attachments/assets/bbee1002-e1a6-44dd-9d0c-ad47a0d22175)](https://osu.ppy.sh/scores/1711867460)

P.S. Sorry if this is what #4 is already referring to. It's extremely vague.

**Comment by EngineerMark** [comment] 2024-07-25 19:12
For the sake of the pr and general info: issue is caused by quickly switching between pages, where the previous page "session" is still loading tags while the next one is doing that too. So tags would get added twice.

It's not really reproducable unless you are going 99 links per second, but needs a fix.

**Comment by EngineerMark** [comment] 2024-07-25 19:25
Fixed on 9deb9cf4adc26933e4005c447c0d53c24f040173

Will come later on main branch and pushed to users.

**Closed as completed by EngineerMark** 2024-07-25 19:25 UTC
